### ISSUE TITLE
Repository Management button

### ISSUE THREAD

**Issue by lharzenetter** [OpenTOSCA/ui#24]
**Current Behavior:**
The Repository Managment button is pointing to the API (`localhost:8080/winery/servicetemplates`)

**Expected Behavior:**
The button should navigate the user to the repository UI  (`localhost:8080/#/servicetemplates`).

**Steps to Reproduce:**

1. Just click the button and you get a JSON response instead of the UI.

**Other Information:**

![grafik](https://user-images.githubusercontent.com/23058331/38373722-2b02054a-38f2-11e8-9541-33ecaeab350a.png)

**System Information:**
OpenTOSCA Docker on Win10

**Comment by mee4895** [comment]
The URL for this button is simply the Repository API so there are multiple ways to fix this.

1. we change the Repository API to localhost:8080 and add everything else where it is used
2. we add a third option to the settings which links to the winery ui
3. we add the link as a hard coded value in the ui (bad option I know but it is the quick way)

@fakepk & @miwurster  what is your opinion on this?

**Comment by koppor** [comment]
The link to the UI can be derived from the "Repository Management" link: Just remove "/winery" at the end. I think, that should suffice.

Thus, the user still configures the API endpoint. The UI URL is transparently derived from it.

**Comment by mee4895** [comment]
I now simply drop the path and only use the host part of the url. See https://github.com/OpenTOSCA/ui/pull/27
