### ISSUE TITLE
Repository UI connection

### ISSUE THREAD

**Issue by lharzenetter** [OpenTOSCA/ui#25]
**Current Behavior:**
The Repository API connection uses `localhost` as a default.

**Expected Behavior:**
Instead, it should use `window.location` per default. Similar to the Container API connection.

**Steps to Reproduce:**

  1. Open the UI with your machine's IP address
  1. Go to the administration tab

**Other Information:**
![grafik](https://user-images.githubusercontent.com/23058331/38374095-2154dfee-38f3-11e8-9456-a81ce41a4c7f.png)

**System Information:**
OpenTOSCA Docker on Win10

**Comment by mee4895** [comment]
@fakepk this issue is solved and ready to be merged.
