### ISSUE TITLE
current version of ui return 404 for GET /

### ISSUE THREAD

**Issue by Legion2** [OpenTOSCA/ui#29]
**Current Behavior:**
GET / return 404

**Expected Behavior:**
the ui should be displayed and not a 404 error page

**Steps to Reproduce:**

  1. use https://github.com/OpenTOSCA/opentosca-docker
  1. docker-compose up -d
  1. wait 5 min
  1. open localhost

**Other Information:**

**System Information:**

**Comment by miwurster** [comment]
Fixed with latest refactorings.
