### ISSUE TITLE
Build Plan still running on DELETED Instance

### ISSUE THREAD

**Issue by mee4895** [OpenTOSCA/ui#4]
**Current Behavior:**
![screenshot from 2017-09-18 17-11-17](https://user-images.githubusercontent.com/13787299/30549456-18fd0394-9c95-11e7-99f2-4704c2bc8dcd.png)

**Expected Behavior:**
Build plan should not be able to be running on a deleted Instance.

**Steps to Reproduce:**

  1. Create a new instance.
  1. Delete the instance while build plan is still running (or hung up because of an error).

**Other Information:**
Tested with the MyTinyToDoDockerContainer.csar

**Comment by miwurster** [comment]
Disable the execution of (management) plans until the instance is created.

**Comment by miwurster** [comment]
No, there are no plans to implement this.
